"use client";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import Modal from "@/components/modal/Modal";

import { Providers } from "./store/provider";

import "@/styles/reset.css";
import "../../styles/global.css";
import React from "react";
import { ToastContainer } from "react-toastify";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body>
          <Header />
          {children}
          <Footer />
          <Modal />
          <ToastContainer
            hideProgressBar={true}
            autoClose={3000}
            position="top-center"
          />
        </body>
      </Providers>
    </html>
  );
}
