"use client";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";

import { Providers } from "./store/provider";

import "@/styles/reset.css";
import "../../styles/global.css";
import React from "react";

import { init } from "./socketio";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  init();
  return (
    <html lang="en">
      <Providers>
        <body>
          <Header />
          {children}
          <Footer />
        </body>
      </Providers>
    </html>
  );
}
