export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";

import "@/styles/reset.css";
import "../../styles/global.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
